### ISSUE TITLE
Cannot replay select2 options selection

### ISSUE THREAD

**Issue by last-hit-b** [last-hit-aab/last-hit#23]
https://select2.org/tagging

**Comment by last-hit-aab** [comment]
a068836a62dba723e1e39a589ac2050db97ab2f0
183fa3b943269c5ef5b369d78dec72688d277770
b8695447bb32cbdf7ff6786f5c68ea0cb53c169c
41973bc962d5c4d5c06c32632765bab55b3a4d87
64f23ceabe4dcc121e328b94e1fd990ace3a2d9c
