### ISSUE TITLE
navigation failed because browser has disconnected

### ISSUE THREAD

**Issue by ilvelh** [last-hit-aab/last-hit#26]
Mac OS  Catalina 10.15 
Last Hit 0.3.7
Node version (v10.16.3 or v11.15.0 or v12.12.0)
When I replay, I got an error alert: "navigation failed because browser has disconnected".
![11](https://user-images.githubusercontent.com/6404992/66851386-38a18180-efad-11e9-9bea-4473d2a594fa.jpg)

**Comment by last-hit-aab** [comment]
Hi, ilvelh
Can you provide the log? it should in path “/Library/Logs/electron” on macOS, If you can provide the recorded script(jsonfile) in your workspace, sholud be better.

**Comment by last-hit-aab** [comment]
@ilvelh we have to close this issue, since we have no enough information to process.
according to the version upgrading, maybe you can use the latest version to try again.

thanks again.
