### ISSUE TITLE
add regexp check for random id

### ISSUE THREAD

**Issue by bradwoo8621** [last-hit-aab/last-hit#27]
Hi,

in our ui components, id is random generated. it will cause replay failure.
should you add a special regexp check when building xpath?

here is the sample.  

currently  
```javascript
const ignoredIdRegexps = [/^md-.+-.{6,16}$/, /^select2-.+$/];
```

wanted  
```javascript
const ignoredIdRegexps = [/^md-.+-.{6,16}$/, /^select2-.+$/, /^rainbow-ui\d{15}$/];
```

`\d{15}` is a timestamp.

**Comment by last-hit-aab** [comment]
@bradwoo8621 sure.

we think `/^.+\d{10,}$/` is better, anyway if there is suffixed with 10 digits, is a random id.

will in next version. cheers!
