### ISSUE TITLE
wechat support

### ISSUE THREAD

**Issue by last-hit-aab** [last-hit-aab/last-hit#35]
- share: open a page directly
- choose image: upload
- geo: alert and input

**Comment by last-hit-b** [comment]
@last-hit-aab, maybe we should support fb first?

**Comment by last-hit-aab** [comment]
@last-hit-b , wechat first, according to the market.

**Comment by last-hit-b** [comment]
@last-hit-aab , got it. will put into task pool.

**Comment by last-hit-b** [comment]
@last-hit-aab, done. geo is pending since no way to input latitude and longitude
