### ISSUE TITLE
Multiple url regexp replacements

### ISSUE THREAD

**Issue by bradwoo8621** [last-hit-aab/last-hit#42]
Hi,

We found there is a url replacement feature in CI, that's great.  
But in our scenarios, in one flow, there are multiple url host need to be replaced, seems not supported yet.

Now we have to replace these urls manually, will you add this feature in next release?

Thanks.

**Comment by last-hit-aab** [comment]
@bradwoo8621 we will see, it not in plan, but seems helpful. will let your know when it is added.

**Comment by last-hit-b** [comment]
@bradwoo8621 , use `&&` to support multiple regexs, will release at 0.4.0

**Comment by bradwoo8621** [comment]
@last-hit-a @last-hit-aab thank you very much.
