### ISSUE TITLE
Add "Run one step" button on replay dialog

### ISSUE THREAD

**Issue by bradwoo8621** [last-hit-aab/last-hit#57]
Sometimes there is no breakpoint on next of breakpointed step, seems have to set breakpoint on each step. 

Or a `Run one step` button is more user friendly on debugging the flow.

**Comment by last-hit-aab** [comment]
@bradwoo8621 good advice, will have that soon.

**Comment by last-hit-b** [comment]
9c0c75d8333216698592b3a227943010169c2f72

**Comment by last-hit-b** [comment]
@bradwoo8621 0.8.1, enjoy
